### ISSUE TITLE
Changing signature?

### ISSUE THREAD

**Issue by Moon-developer** [nchie/valheim-server-patch#2]
What do the signatures represent exactly? would like to modify it to change values manually to either increase or decrease :thinking:

**Comment by Moon-developer** [comment]
I see the game just got updated to add this fix so the script now fails hence asking for a method to manually change signature in the off chance the increase by the valheim devs isn't enough and we would like a slight increase

**Comment by nchie** [comment]
Looks like it stopped working because the `m_dataPerSecond` variable which the script updated isn't even there anymore, so unless I'm wrong about that, I don't think this script is going to be of much help after this patch. If there turns out that there exists some other simple change in the code that reduces lag a lot, I could probably write a patch script for that quite easily. 
I likely won't look into it myself as I've finished all the content that's out in the game currently, but feel free to ping me if another fix involving dnSpy shows up somewhere.


Anyways, a simple explanation on how this script worked, and how to do it on your own ([because teach a man to fish blabla](https://en.wiktionary.org/wiki/give_a_man_a_fish_and_you_feed_him_for_a_day;_teach_a_man_to_fish_and_you_feed_him_for_a_lifetime)):

The signature `\x20\x00\xF0\x00\x00` was the instruction which set `m_dataPerSec` to `0x0000F000` (or 61440). `\x` is the way to represent a byte inside a string in Python, so `\x20` equals `0x20`.

`\x00\xF0\x00\x00` is `0x0000F000` (61440 in hex) in reverse because the x86/x86-64 architectures are [little endian](https://en.wikipedia.org/wiki/Endianness). The `\x20` is the opcode for the instruction.

You can find the instruction quite easily in dnSpy by 

1. Viewing the decompiled source code where you want to make the change
2. Right clicking the relevant row and press `Edit IL Instructions`.
3. Find the exact instruction which actually does the thing you're interested in changing, right-click it and choose `Copy File Offsets`.
4. Open the file in a Hex editor (the one inside dnSpy works well), go to the offset you just copied (CTRL+G or right-click -> `Go to Offset`.
5. Find the bytes which represent the exact value you want to change. For example in my case it was `\x00\xF0\x00\x00` which I wanted to change to `\x00\x00\x04\x00`. The problem was that `\x00\xF0\x00\x00` wasn't unique in the file which meant I couldn't use it as the signature, so I needed to add more to the search. Luckily I found that just adding the byte which came just before the value (the opcode) was enough for the search to result in 1 unique match, hence the `\x20`.

### Edit: 
From a 5 minute glance at the disassembled code, if there's anything that needs patching, I'd guess it's this line of code in the `SendZDOs` method inside `ZDOMan`.
```
	int num = 10240 - sendQueueSize;
```
It seems to be used in the same way as before in the `while` loop (though it used to be a `for` loop), but hopefully this new value will work better than the value which was there before (`int num = this.m_dataPerSec / 20;`).

**Comment by Moon-developer** [comment]
Thank you for the detailed explanation. Even though we can't do any small patches with the new update just knowing how you originally did it was quite insightful and look forward to using this sort of method in other places if the need arises that is. Also well done on coming up with this method. It came in handy since I couldn't install DNSPY on my linux server to edit the file. Had to copy things back and forth manually.
